export default [
    {
        id:1,
        name:'Programming',
        icon:'/coding.png',
        prompt:''
    },
    {
        id:2,
        name:'Health',
        icon:'/lotus.png',
        prompt:''
    },
    {
        id:3,
        name:'Creaaive',
        icon:'/creative.png',
        prompt:''
    }
]